Finance/Controllers/HistoryController.cs
using Finance.DAM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Finance.Controllers
{
    [Authorize]
    public class HistoryController : APIBase
    {
        [HttpGet]
        [Route("email={email}")]
        public async Task<ActionResult<object>> GetAllCateByEmail(string email)
        {
            var list = await DAM.CategoryDAM.ListCategory(email);
            return list;

        }

        [HttpGet]
        [Route("transaction/email={email}&type={type}")]
        public async Task<ActionResult<object>> GetAllTransactionByType(string email, string type)
        {
            var list = await DAM.TransactionDAM.ListTransactionByType(email, type);
            return list;
        }

        [HttpGet]
        public async Task<ActionResult<object>> GetCate([FromQuery] string email, [FromQuery] string categoryId)
        {
            var category = await DAM.CategoryDAM.GetCategory(email, categoryId);
            if (category == null) return new
            {
                title = "Category was not found",
                email = email,
            };
            return category;
        }
    }
}

Finance/Pages/Admin/Feedback.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Finance.Pages.Admin
{
    public class FeedbackModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Finance/Pages/Admin/SupportUser.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Finance.DAM;
using Finance.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Serilog;

namespace Finance.Pages.Admin
{
    [Authorize("AdminOnly")]
    public class SupportUser : PageModel
    {
        public List<String> ActiveUser { get; set; }
        public List<Support> ActiveSupport { get; set; }
        public Boolean queryEmail { get; set; }
        public String chattingEmail { get; set; }
        public async Task OnGetAsync()
        {
            var userEmail = Request.Query["userEmail"].FirstOrDefault("admin");
            ActiveUser = await SupportDAM.GetAllUserInbox();
            ActiveSupport = new List<Support>();
            foreach (var item in ActiveUser)
            {
                var listSupport = await SupportDAM.LastMessageFromUser(item);
                ActiveSupport.Add(listSupport[0]);
            }
            var _find = ActiveUser.Find(e => e == userEmail);
            if (userEmail == "admin" || ActiveUser.Find(e => e == userEmail) == null)
            {
                queryEmail = true;
                chattingEmail = "";
            }
            else
            {
                queryEmail = false;
                chattingEmail = userEmail;
            }
        }
    }
}

Finance/Pages/_Component/Home/History/Form.cshtml.cs
using Finance.DAM;
using Finance.Model;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using System.Text.Json;
using Transaction = Finance.Model.Transaction;

namespace Finance.Pages._Component.Home.History
{
    public class FormModel : _CompModel
    {
        public List<Category> ListCate { get; set; } = new();
        DateTime n = DateTime.Now;
        public string LocalDate;
        public string? Delete { get; set; } = "";
        public Transaction? Transaction { get; set; } = new();
        public class FormRecord
        {
            [BindProperty]
            public int Id { get; set; }
            [BindProperty]
            public DateTime Date { get; set; }
            [BindProperty]
            public String CateId { get; set; }
            [BindProperty]
            public String Desc { get; set; }
            [BindProperty]
            public Double Amount { get; set; }

        }

        [BindProperty]
        public FormRecord f { get; set; } = new FormRecord();

        public async Task<IActionResult> OnPost([FromBody] JsonElement json)

        {
            var transactionId = json.GetProperty("transactionId").GetInt32();
            var email = json.GetProperty("email").GetString();
            var cateType = json.GetProperty("cateType").GetString();
            try
            {
                Delete = json.GetProperty("delete").GetString();
            }
            catch (KeyNotFoundException)
            {
                Delete = "";
            }
            ListCate = await CategoryDAM.ListCategoryByType(email, cateType);
            Transaction = await TransactionDAM.GetTransaction(email, transactionId);
            if (Transaction != null)
            {
                f.Id = Transaction.Id;
                f.CateId = Transaction.Category.Id.ToString();
                f.Date = Transaction.Date;
                f.Desc = Transaction.Description;
                f.Amount = Transaction.Amount;
                string month = Transaction.Date.Month >= 10 ? Transaction.Date.Month + "" : "0" + Transaction.Date.Month;
                string day = Transaction.Date.Day >= 10 ? Transaction.Date.Day + "" : "0" + Transaction.Date.Day;
                string hour = Transaction.Date.Hour >= 10 ? Transaction.Date.Hour + "" : "0" + Transaction.Date.Hour;
                string minute = Transaction.Date.Minute >= 10 ? Transaction.Date.Minute + "" : "0" + Transaction.Date.Minute;
                LocalDate = $"{Transaction.Date.Year}-{month}-{day}T{hour}:{minute}";
            }
            return Page();
        }

        public async Task<IActionResult> OnPostDelete([FromQuery] int id, [FromQuery] string type)
        {
            await TransactionDAM.DeleteTransaction(id);
            string url = type == "income" ? "~/account/history?IncomeCheck=true" : "~/account/history";
            return Redirect(url);
        }

        public async Task<IActionResult> OnPostUpdate([FromQuery] int id, [FromQuery] string type)
        {
            await TransactionDAM.UpdateTransaction(id, f.Date, f.CateId, f.Desc, f.Amount);
            string url = type == "income" ? "~/account/history?IncomeCheck=true" : "~/account/history";
            return Redirect(url);
        }
    }
}

Finance/Pages/_Component/Home/Wallet/Form.cshtml.cs
using Finance.DAM;
using Finance.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;

namespace Finance.Pages._Component.Home.Wallet
{
    public class FormModel : _CompModel
    {
        public List<Category> ListCate { get; set; } = new();
        DateTime n = DateTime.Now;
        public string LocalDate;
        public class FormRecord
        {
            [BindProperty]
            public DateTime Date { get; set; }
            [BindProperty]
            public String CateId { get; set; }
            [BindProperty]
            public String Desc { get; set; }
            [BindProperty]
            public Double Amount { get; set; }

        }

        [BindProperty]
        public FormRecord f { get; set; } = new FormRecord();

        public async Task<IActionResult> OnPost([FromBody] JsonElement json)

        {
            LocalDate = $"{n.Year}-{n.Month}-{n.Day}T{n.Hour}:{n.Minute}";

            var email = json.GetProperty("email").GetString();
            var cateType = json.GetProperty("cateType").GetString();

            ListCate = await CategoryDAM.ListCategoryByType(email, cateType);
            return Page();
        }
    }
}

Finance/Pages/_Component/Home/Wallet/InsertCate.cshtml.cs
using Finance.DAM;
using Finance.Model;
using Finance.Services;
using Finance.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Serilog;
using System.Text.Json;

namespace Finance.Pages._Component.Home
{
    public class InsertCateModel : _CompModel
    {

        public Account Account { get => Identity.Get(HttpContext); }

        public IActionResult OnGet()
        {
            return Page();
        }
        public List<Category> ListCate { get; set; } = new();


        public async Task<IActionResult> OnPostInsert([FromBody] JsonElement json)
        {
            var cateName = json.GetProperty("cateName").GetString();
            var cateType = json.GetProperty("cateType").GetString();
            await CategoryDAM.Insert(cateName, cateType, 1, Account.Email);
            ListCate = await CategoryDAM.ListCategoryByType(Account.Email, cateType);

            return Page();
        }

        public async Task<IActionResult> OnPostUpdate([FromBody] JsonElement json)
        {
            // id, name, color, className: class_name
            // iconId, iconClassName
            var id = json.GetProperty("id").GetInt32();
            var cateName = json.GetProperty("name").GetString();
            var cateType = json.GetProperty("cateType").GetString();
            var cateColor = json.GetProperty("color").GetString();
            var iconClassName = json.GetProperty("className").GetString();
            var iconId = json.GetProperty("iconId").GetInt32();


            await CategoryDAM.Update(id, cateName, iconId, cateColor);
            ListCate = await CategoryDAM.ListCategoryByType(Account.Email, cateType);

            return Page();
        }

        public async Task<IActionResult> OnPostDelete([FromBody] JsonElement json)
        {
            var id = json.GetProperty("id").GetInt32();
            var cateType = json.GetProperty("cateType").GetString();

            await CategoryDAM.Delete(id);
            ListCate = await CategoryDAM.ListCategoryByType(Account.Email, cateType);

            return Page();
        }
    }
}

Finance/Pages/account/Feedback.cshtml.cs
using Finance.DAM;
using Finance.Model;
using Finance.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace Finance.Pages
{
    [Authorize]
    public class FeedbackModel : PageModel
    {
        public Account Account { get => Identity.Get(HttpContext); }

        [BindProperty]
        [Required, StringLength(50, MinimumLength = 5)]
        public string Title { get; set; } = "";

        [BindProperty]
        [Required, StringLength(100, MinimumLength = 5)]
        public string Detail { get; set; } = "";

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                await FeedbackDAM.Insert(Account.Email, Title, Detail);
                TempData["feedbackSent"] = true;
            }
            return Page();
        }
    }
}

Finance/Pages/account/Logout.cshtml.cs
using Finance.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Finance.Pages
{
    [Authorize]
    public class LogoutModel : PageModel
    {
        public async Task<IActionResult> OnGetAsync()
        {
            await Identity.Logout(HttpContext);
            return Redirect(Request.Query["ReturnUrl"].FirstOrDefault("/"));
        }
    }
}

Finance/Pages/account/Profile.cshtml.cs
using Finance.DAM;
using Finance.Model;
using Finance.Services;
using Finance.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Serilog;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Finance.Pages
{
    [Authorize]
    public class ProfileModel : PageModel
    {
        public class FormInfoModel
        {
            [BindProperty]
            [Required, StringLength(60, MinimumLength = 3, ErrorMessage = "Name length must be between 3 and 60")]
            public string DisplayName { get; set; } = "";

            [BindProperty]
            public IFormFile? AvatarUpload { get; set; }
        }
        public class FormPasswordModel
        {
            [BindProperty]
            [Required, StringLength(60, MinimumLength = 5, ErrorMessage = "Length must be between 5 and 60")]
            public string OldPassword { get; set; } = "";

            [BindProperty]
            [Required, StringLength(60, MinimumLength = 5, ErrorMessage = "Length must be between 5 and 60")]
            public string Password { get; set; } = "";

            [BindProperty]
            [Required, DisplayName("Confirm password"), Compare("Password")]
            public string RePassword { get; set; } = "";
        }

        public Account Account { get => Identity.Get(HttpContext); }

        [BindProperty]
        public FormPasswordModel FormPassword { get; set; } = new();

        [BindProperty]
        public FormInfoModel FormInfo { get; set; } = new();

        public ProfileModel() : base()
        {

        }

        public void OnGet()
        {
            FormInfo.DisplayName = Account.DisplayName;
        }

        public async Task<IActionResult> OnPostUpdateInfo()
        {
            ModelState.Clear();
            if (!TryValidateModel(FormInfo, nameof(FormInfo)))
            {
                TempData.Remove("profileUpdateSuccess");
                return Page();
            }

            if (FormInfo.AvatarUpload != null)
            {
                var resp = await Helper.UploadFile("/Finance", FormInfo.AvatarUpload);
                Account.AvatarUrl = resp.URL;
            }
            Account.DisplayName = FormInfo.DisplayName;
            await AccountDAM.UpdateInfo(Account);

            TempData["profileUpdateSuccess"] = "Updated information successfully";
            return Page();
        }

        public async Task<IActionResult> OnPostUpdatePassword()
        {
            FormInfo.DisplayName = Account.DisplayName;
            ModelState.Clear();
            if (!TryValidateModel(FormPassword, nameof(FormPassword)))
            {
                TempData.Remove("profileUpdateSuccess");
                ViewData["openPassForm"] = true;
                return Page();
            }

            if (!await AccountDAM.Verify(Account.Email, FormPassword.OldPassword))
            {
                ModelState.AddModelError("FormPassword.OldPassword", "Old password is incorrect");
                TempData.Remove("profileUpdateSuccess");
                ViewData["openPassForm"] = true;
                return Page();
            }

            await AccountDAM.UpdatePassword(Account.Email, FormPassword.Password);
            TempData["profileUpdateSuccess"] = "Password changed successfully";
            return Page();
        }
    }
}

Finance/Pages/account/SupportUser.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Finance.Model;
using Finance.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Finance.Pages.account
{

    [Authorize]
    public class SupportUser : PageModel
    {
        public Account Account { get => Identity.Get(HttpContext); }
        public void OnGet()
        {
        }
    }
}

Finance/Pages/account/Feedback.cshtml
@page
@model Finance.Pages.FeedbackModel
@{
	Layout = "";
}

<!DOCTYPE html>
<html lang="en">
<head>
  <link href="https://kit-pro.fontawesome.com/releases/v5.15.4/css/pro.min.css" rel="stylesheet" />

	<title>Feedback</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="/feedback/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/feedback/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/feedback/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/feedback/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/feedback/vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/feedback/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/feedback/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/feedback/vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/feedback/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
    <link rel="stylesheet" href="~/asset/css/iziToast.min.css" rel="stylesheet" />
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/feedback/css/util.css">
	<link rel="stylesheet" type="text/css" href="/feedback/css/main.css">
<!--===============================================================================================-->
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
</head>
<body>
	<div class="container-contact100">
		<div class="wrap-contact100">
			<form class="contact100-form validate-form" method="post">
				<span class="contact100-form-title animate__animated animate__fadeIn">
					<a class="btn btn-primary" href="/account" id="back-btn">
						<i class="fal fa-chevron-left"></i>
					</a>
					Send Us A Message
				</span>
					
				@if (TempData["feedbackSent"] is not null)
				{
					<div class="animate__animated animate__fadeInLeftBig" style="margin-bottom: 16px; color: #25A56A99; display: flex; gap: 8px;">
						<div>
							Thank you, your feedback has been sent!
						</div>
						<div class="animate__animated animate__fadeIn animate__delay-1s">
							<i class="fal fa-check"></i> 
						</div>
					</div>
				}

				<div class="wrap-input100 validate-input disable-item" data-validate="Name is required">
					<label class="label-input100" for="name">Full name</label>
					<input value="@Model.Account.DisplayName" disabled class="input100" type="text">
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-input100 validate-input disable-item" data-validate = "Valid email is required: ex@abc.xyz">
					<label class="label-input100" for="email">Email Address</label>
					<input value="@Model.Account.Email" disabled class="input100" type="text">
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate = "Title is required">
					<label class="label-input100" asp-for="Title">Title</label>
					<input asp-for="Title" class="input100" type="text" placeholder="Enter issue title...">
					<span class="focus-input100"></span>
					<span class="text-danger" style="display: inline-block; padding: 20px;" asp-validation-for="Title"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate = "Detail infomation is required">
					<label class="label-input100" asp-for="Detail">Detail</label>
					<textarea asp-for="Detail" class="input100" placeholder="Type your message here..."></textarea>
					<span class="focus-input100"></span>
					<span class="text-danger" style="display: inline-block; padding: 20px;" asp-validation-for="Detail"></span>
				</div>

				<div class="container-contact100-form-btn  animate__animated animate__fadeInUp">
					<button class="contact100-form-btn">
						Send
					</button>
				</div>

				<div class="contact100-form-social flex-c-m" >
					<a href="#" class="contact100-form-social-item flex-c-m bg1 m-r-5">
						<i class="fa fa-facebook-f" aria-hidden="true"></i>
					</a>

					<a href="#" class="contact100-form-social-item flex-c-m bg2 m-r-5">
						<i class="fa fa-twitter" aria-hidden="true"></i>
					</a>

					<a href="#" class="contact100-form-social-item flex-c-m bg3">
						<i class="fa fa-youtube-play" aria-hidden="true"></i>
					</a>
				</div>
			</form>

			<div class="contact100-more flex-col-c-m" style="background-image: url('/feedback/images/bg-01.jpg');">
			</div>
		</div>
	</div>

<!--===============================================================================================-->
	<script src="/feedback/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="/feedback/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="/feedback/vendor/bootstrap/js/popper.js"></script>
	<script src="/feedback/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="/feedback/vendor/select2/select2.min.js"></script>
	<script>
		$(".js-select2").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect2')
			});
		})
		$(".js-select2").each(function(){
			$(this).on('select2:open', function (e){
				$(this).parent().next().addClass('eff-focus-selection');
			});
		});
		$(".js-select2").each(function(){
			$(this).on('select2:close', function (e){
				$(this).parent().next().removeClass('eff-focus-selection');
			});
		});

	</script>
<!--===============================================================================================-->
	<script src="/feedback/vendor/daterangepicker/moment.min.js"></script>
	<script src="/feedback/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="/feedback/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="~/asset/js/signalr.min.js"></script>
	<script src="~/asset/js/iziToast.min.js"></script>
<!--===============================================================================================-->

	<script src="/feedback/js/main.js"></script>

	<script>
		function connectWS(startCb = () => { }) {
			var conn = new signalR.HubConnectionBuilder().withUrl("/_ws").build();
			conn.start().then(() => startCb(conn));
			return conn;
		}

		(() => {
			const toastCfg = {
				position: "topRight",
				closeOnClick: true,
				closeOnClick: true,
				pauseOnHover: false,
				layout: 2,
				timeout: 3000
			}

			window.toast_success = (title, message) => {
				iziToast.show({
					...toastCfg,
					title: title,
					message: message,
					color: "green",
					icon: "fal fa-check",
					iconColor: "#32CD32"
				});
			}

			window.toast_error = (title, message) => {
				iziToast.show({
					...toastCfg,
					title: title,
					message: message,
					color: "red",
					icon: "fal fa-exclamation",
					iconColor: "#D2001A"
				});
			}
		})();
	</script>

	<script>
		@if (TempData["feedbackSent"] != null)
		{
			<text>
				toast_success("Feedback was sent", "Thank you for your help");

				connectWS(conn => {
					conn.invoke("SendMessage");
				});
			</text>
		}
	</script>
</body>
</html>

Finance/Pages/account/Logout.cshtml
@page
@model LogoutModel
@{
}

<p>Your are logging out...</p>

Finance/Pages/account/Profile.cshtml
@page
@using Finance.Utils
@model ProfileModel
@{
    Layout = "_HomeLayout";
    
    ViewData["Title"] = "Profile";
}

@section Css {
    <style>
        ul.timeline {
            list-style-type: none;
            position: relative;
        }

            ul.timeline:before {
                content: ' ';
                background: #d4d9df;
                display: inline-block;
                position: absolute;
                left: 29px;
                width: 2px;
                height: 100%;
                z-index: 400;
            }

            ul.timeline > li {
                margin: 30px;
                padding-left: 20px;
            }

            ul.timeline > li:before {
                content: ' ';
                background: white;
                display: inline-block;
                position: absolute;
                border-radius: 50%;
                border: 3px solid #22c0e8;
                left: 20px;
                width: 20px;
                height: 20px;
                z-index: 400;
            }

            .avatar {
                width: 100px;
                height: 100px;
                object-fit: contain;
                box-shadow: rgba(0, 0, 0, 0.16) 0px 10px 36px 0px, rgba(0, 0, 0, 0.06) 0px 0px 0px 1px;
            }

            .avatar:hover {
                cursor: pointer;
            }

            .change-password {
                display: flex;
                flex-direction: column;
                gap: 20px;
            }

            .change-password-header > i {
                transition: .3s;
            }

            .change-password-header:hover > i {
                translate: 10px 0;
            }
    </style>
}

 @{
    var avatarUrl = Helper.GetImage(Model.Account.AvatarUrl, new Imagekit.Transformation().Width(100).Height(100));
}

<div class="container p-5">
    <div class="row p-3">
        <div class="col-lg-6 p-4">
            <form class="d-flex flex-column" style="gap: 15px;" method="post" enctype="multipart/form-data" asp-page-handler="UpdateInfo" >
                <span class="fs-3 fw-bold">User information</span>
                <div class="d-flex justify-content-center">
                    <img class="rounded-circle avatar" src="@avatarUrl" alt="Avatar" onclick="changeAvatar(this)">
                    <input asp-for="FormInfo.AvatarUpload" hidden accept="image/*" />
                </div>

                <div>
                    <label>Email</label>
                    <input value="@Model.Account.Email" class="form-control" disabled>
                </div>

                <div>
                    <label>Display name</label>
                    <input asp-for="FormInfo.DisplayName" class="form-control" required>
                    <span asp-validation-for="FormInfo.DisplayName" class="form-text text-danger"></span>
                </div>

                <div class="row" style="gap: 10px;">
                    <div class="col">
                        <button type="submit" class="btn btn-primary w-100">Update your info</button>
                    </div>
                    <div class="col">
                        <button type="reset" class="btn btn-info text-white w-100">Reset</button>
                    </div>
                </div>
            </form>

            
            <div class="mt-5">
                <form class="d-flex flex-column" style="gap: 15px;" method="post" asp-page-handler="UpdatePassword">
                    <div>
                        <a class="fs-4 fw-bold change-password-header" id="openPassForm" data-bs-toggle="collapse" href="#changePassword" style="gap: 15px; text-decoration: none;">
                            <span class="d-inline-block me-1">Change Password</span>
                            <i class="fal fa-chevron-double-down"></i>
                        </a>
                    </div>

                    <div class="collapse change-password" id="changePassword">
                        <div>
                            <div class="input-group">
                                <span class="input-group-text">Old Password</span>
                                <input asp-for="FormPassword.OldPassword" type="password" class="form-control" placeholder="Old Password" required>
                            </div>
                            <span asp-validation-for="FormPassword.OldPassword" class="form-text text-danger"></span>
                        </div>

                        <div>
                            <div class="input-group">
                                <span class="input-group-text">New Password</span>
                                <input asp-for="FormPassword.Password" type="password" class="form-control" placeholder="Password" required>
                            </div>
                            <span asp-validation-for="FormPassword.Password" class="form-text text-danger"></span>
                        </div>

                        <div>
                            <div class="input-group">
                                <span class="input-group-text">Confirm Password</span>
                                <input asp-for="FormPassword.RePassword" type="password" class="form-control" placeholder="Confirm Password" required>
                            </div>
                            <span asp-validation-for="FormPassword.RePassword" class="form-text text-danger"></span>
                        </div>

                        <div class="row" style="gap: 10px;">
                            <div class="col-6">
                                <button type="submit" class="btn btn-danger w-100">Confirm change</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-6 p-4">
            <span class="fs-3 fw-bold">Activities</span>

            <ul class="timeline">
                <li>
                    <a style="color: #034079;font-weight: bold;">Account created</a>
                    <a class="float-right" style="color: #034079;">@Model.Account.CreatedAt</a>
                    <p>Login</p>
                </li>
                <li>
                    <a style="color: #21a7d0;font-weight: bold;">Last active</a>
                    <a class="float-right" style="color: #21a7d0;">@Model.Account.LastActive</a>
                    <p>Login</p>
                </li>
            </ul>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        function changeAvatar(target) {
            const uploadAvt = $q("#FormInfo_AvatarUpload");

            uploadAvt.onchange = function () {
                if (this.files && this.files[0]) {
                    const file = this.files[0];
                    target.src = URL.createObjectURL(file);
                    target.onload = function () {
                        URL.revokeObjectURL(target.src) // free memory
                    }
                }
            }

            uploadAvt.click();
        }

        @if (TempData["profileUpdateSuccess"] != null)
        {
            <text>
                toast_success("Success", "@TempData["profileUpdateSuccess"]");
            </text>
        }

        @if (ViewData["openPassForm"] != null) {
            <text>
                $q("#openPassForm").click();
            </text>
        }
    </script>
}